jobs:
  include:
    - language: java
      jdk: openjdk11
      script:
        - cd server
        - ./gradlew build

    - language: node_js
      node_js: 14
      script:
        - cd client
        - yarn install
        - yarn test
