jobs:
  include:
    - language: java
      jdk: openjdk11
      script:
        - cd server
        - ./gradlew build

    - language: node_js
      node_js: 14
      script:
        - cd client
        - yarn install
        - yarn test
        - PUBLIC_URL=$public_url REACT_APP_BASE_URL=$app_base_url yarn build
      deploy:
        provider: s3
        access_key_id: $access_key_id
        secret_access_key: $secret_access_key
        bucket: $bucket
        skip_cleanup: true
        local_dir: build
        on:
          branch: main
