# Used in swagger ui
version: 1.0.0

# Default profile
spring:
  profiles:
    active: local
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoint:
    health:
      show-details: always

service:
  authorization:
    token-valid-for: 120 # 2 hours
  seconds-to-timeout: 120 # 2 minutes