AWSTemplateFormatVersion: "2010-09-09"
Description: "Sanity check environment"
Resources:
  DatabaseDumpEnv:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: DatabaseDumpEnv
      ComputeResources:
        MinvCpus: 0
        MaxvCpus: 4
        DesiredvCpus: 1
        SecurityGroupIds:
          -
        Type: SPOT
        Subnets:
          -
        InstanceRole: ecsInstanceRole
        AllocationStrategy: SPOT_CAPACITY_OPTIMIZED
        InstanceTypes:
          - optimal
      State: ENABLED
  DatabaseDumpQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref DatabaseDumpEnv
      JobQueueName: DatabaseDumpQueue
      Priority: 1
      State: ENABLED
# export variables then
# aws cloudformation deploy --template-file aws/cloudformation.yaml --stack-name database-dump --capabilities CAPABILITY_IAM --region us-west-2
