name: Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
  pull_request:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/client/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/client/yarn.lock') }}

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Yarn Install
        working-directory: ./client
        run: yarn install
      - name: Build
        working-directory: ./client
        run: yarn build
      - name: Unit Tests
        working-directory: ./client
        run: yarn test
