name: Test frontend

on:
  push:
    branches-ignore:
      - "main" # Already tested by deploy
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Yarn Install
        working-directory: ./client
        run: yarn install
      - name: Build
        working-directory: ./client
        run: yarn build
      - name: Unit Tests
        working-directory: ./client
        run: yarn test
